# Generated by Django 2.0.7 on 2018-07-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(default='请填写标题', max_length=32, verbose_name='照片标题')),
                ('pic', models.ImageField(upload_to='', verbose_name='照片')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '相册',
                'db_table': 'tb_album',
                'verbose_name': '相册',
            },
        ),
    ]
