# Generated by Django 2.0.7 on 2018-07-18 05:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, verbose_name='分类名称')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'db_table': 'tb_categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment_author', models.CharField(max_length=20, verbose_name='评论作者')),
                ('comment_avatar', models.ImageField(default='/group1/M00/00/00/CpIAA1tKscSAOfSlAATk7sl35Mk080.png', upload_to='', verbose_name='用户头像头像')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('comment_content', models.CharField(default='评论测试', max_length=500, verbose_name='评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'tb_comments',
            },
        ),
        migrations.CreateModel(
            name='MainPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('main_pic', models.ImageField(default='', upload_to='', verbose_name='轮播图')),
                ('is_delete', models.BooleanField(default=False, verbose_name='下架')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'tb_main_pic',
            },
        ),
        migrations.CreateModel(
            name='SubscribeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('email', models.CharField(max_length=64, verbose_name='订阅邮箱')),
                ('is_delete', models.BooleanField(default=False, verbose_name='退订')),
            ],
            options={
                'verbose_name': '订阅邮箱',
                'verbose_name_plural': '订阅邮箱',
                'db_table': 'tb_subscribe',
            },
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(default='无标题', max_length=64, verbose_name='文章标题')),
                ('author', models.CharField(default='admin', max_length=20, verbose_name='作者')),
                ('summary', models.CharField(default='无摘要', max_length=500, verbose_name='摘要')),
                ('feature_pic', models.ImageField(default='', upload_to='', verbose_name='文章特征图')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='文章正文')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Category', verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'tb_writings',
            },
        ),
        migrations.AddField(
            model_name='mainpic',
            name='writing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Writing', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Writing', verbose_name='所属文章'),
        ),
    ]
