# Generated by Django 2.0.7 on 2018-07-10 04:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, verbose_name='分类名称')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(default='无标题', max_length=64, verbose_name='文章标题')),
                ('author', models.CharField(default='admin', max_length=20, verbose_name='作者')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='文章正文')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Category', verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'writings',
            },
        ),
    ]
