# Generated by Django 2.0.7 on 2018-07-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='read_count',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
