# Generated by Django 2.0.7 on 2018-07-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180710_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment_author', models.CharField(max_length=20, verbose_name='评论作者')),
                ('comment_avatar', models.CharField(default='default.jpg', max_length=64, verbose_name='评论头像')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
            },
        ),
        migrations.AddField(
            model_name='writing',
            name='summary',
            field=models.CharField(default='无摘要', max_length=500, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Writing', verbose_name='所属文章'),
        ),
    ]
