# Generated by Django 2.0.7 on 2018-07-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180711_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(default='评论测试', max_length=500, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_avatar',
            field=models.ImageField(default='/group1/M00/00/00/CpIAA1tKscSAOfSlAATk7sl35Mk080.png', upload_to='', verbose_name='用户头像头像'),
        ),
    ]
