# Generated by Django 2.0.7 on 2018-07-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_subscribeemail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='tb_comments',
        ),
        migrations.AlterModelTable(
            name='subscribeemail',
            table='tb_subscribe',
        ),
    ]
