# Generated by Django 2.0.7 on 2018-07-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180716_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论量'),
        ),
    ]
