# Generated by Django 2.0.7 on 2018-07-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_writing_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('main_pic', models.ImageField(default='', upload_to='', verbose_name='轮播图')),
                ('is_delete', models.BooleanField(default=False, verbose_name='下架')),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Writing', verbose_name='文章')),
            ],
            options={
                'db_table': 'tb_main_pic',
                'verbose_name_plural': '轮播图',
                'verbose_name': '轮播图',
            },
        ),
    ]
